name: Build and deploy Node.js app to Azure Web App - test-react

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C19DDA3DBE74E4FAA966EADE1AD08D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_34FBF3396FDB4D14B33A30E20E5D8AB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EB0F986F7EB841B7BE8D65A5F7B94789 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-react'
          slot-name: 'Production'
          package: ./dist